apiVersion: apps/v1
kind: Deployment

metadata:
  name: afo-backend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: afo-backend

  template:
    metadata:
      labels:
        app: afo-backend

    spec:
      containers:
      - name: afo-backend

        image: nuthan22/my-app:bc53f9ad074e09196629b2210f1de59579959860

        imagePullPolicy: Always

        ports:
        - containerPort: 3000
