apiVersion: apps/v1
kind: Deployment

metadata:
  name: afo-backend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: afo-backend

  template:
    metadata:
      labels:
        app: afo-backend

    spec:
      containers:
      - name: afo-backend

        image: nuthan22/my-app:22668f1c03220870088223e62584bcc98016800e

        imagePullPolicy: Always

        ports:
        - containerPort: 3000
