apiVersion: apps/v1
kind: Deployment

metadata:
  name: afo-backend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: afo-backend

  template:
    metadata:
      labels:
        app: afo-backend

    spec:
      containers:
      - name: afo-backend

        image: nuthan22/my-app:38a8e447fe7bcec35301da0a77911b4f7960f8bf

        imagePullPolicy: Always

        ports:
        - containerPort: 3000
