name: Afo-Cipipe

on: 
    push:
        branches: 
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4            
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with: 
                node-version: '14'

            - name: Install NodeJS dependencies
              run: npm install
